from repository.in_memory.product_repository import ProductRepository
from repository.in_memory.user_repository import UserRepository
from repository.in_memory.ingredient_repository import IngredientRepository
from repository.in_memory.menu_item_repository import MenuItemRepository
from repository.in_memory.foodtruck_repository import FoodtruckRepository
from repository.in_memory.event_repository import EventRepository
from repository.in_memory.receipt_repository import ReceiptRepository
